name: BMO OpenAPI spec

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            openapi

      - name: bundle OpenAPI spec
        uses: ./.github/actions/redocly-bundle
        with:
          apis: openapi/openapi.yaml
          output: openapi/bundled.yaml

      - name: install vacuum
        run: npm i -g @quobix/vacuum

      - name: run vacuum lint
        run: vacuum lint openapi/bundled.yaml
